# Generated by Django 6.1.1 on 2026-10-04 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=60)),
                ('emoji', models.CharField(default='🍽️', max_length=4)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('rating', models.FloatField(default=4.0)),
                ('delivery_minutes', models.PositiveIntegerField(default=30)),
                ('delivery_fee', models.PositiveIntegerField(default=30, help_text='Rupees. 0 means free delivery')),
                ('min_order', models.PositiveIntegerField(default=100, help_text='Minimum item total, in rupees')),
                ('pure_veg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text='e.g. Starters, Mains, Desserts', max_length=50)),
                ('section_order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Rupees')),
                ('veg', models.BooleanField(default=True)),
                ('bestseller', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['section_order', 'name'],
            },
        ),
    ]
