# Generated by Django 6.1.1 on 2026-10-02 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('principal', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rate', models.FloatField(help_text='Interest rate, % per year', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('years', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
