# Generated by Django 6.1.1 on 2026-10-03 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('plays', models.PositiveBigIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(help_text='Length in seconds')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artist.artist')),
            ],
            options={
                'ordering': ['-plays'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='playlist.song')),
            ],
        ),
    ]
